# Generated by Django 3.0.4 on 2020-03-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30)),
                ('num', models.CharField(max_length=8)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_on', models.DateField()),
                ('date_of', models.DateField()),
                ('book_name', models.CharField(max_length=30)),
                ('book_id', models.CharField(max_length=8)),
                ('book_author', models.CharField(max_length=30)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Visitor')),
            ],
        ),
    ]
