# Generated by Django 3.0.4 on 2020-03-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='book_author',
            new_name='Автор книги',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='date_of',
            new_name='Дата возврата',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='date_on',
            new_name='Дата обращения',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='book_id',
            new_name='Код книги',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='book_name',
            new_name='Название книги',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='visitor',
            new_name='Посетитель',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='birthday',
            new_name='День рождения',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='num',
            new_name='Номер билета',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='gender',
            new_name='Пол',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='fio',
            new_name='ФИО Посетителя',
        ),
    ]
