# Generated by Django 3.0.4 on 2020-03-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200323_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='Автор книги',
            new_name='book_author',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='Код книги',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='Название книги',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='Дата возврата',
            new_name='date_of',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='Дата обращения',
            new_name='date_on',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='Посетитель',
            new_name='visitor',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='День рождения',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='ФИО Посетителя',
            new_name='fio',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='Пол',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='Номер билета',
            new_name='num',
        ),
    ]
